var thMappings = [

  /* =========== root links ajax simple responses ========== */
  ["/genres", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/soundtracks", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/thematic-compilations", thRequestResponsesPath + "/item-content-ajax-response.html"],

  /* =========== thematic-compilations songs ajax simple responses ========== */         
  ["/thematic-compilations/1/songs", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/thematic-compilations/2/songs", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/thematic-compilations/3/songs", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/thematic-compilations/4/songs", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/thematic-compilations/5/songs", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/thematic-compilations/6/songs", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/thematic-compilations/7/songs", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/thematic-compilations/8/songs", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/thematic-compilations/9/songs", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/thematic-compilations/10/songs", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/thematic-compilations/11/songs", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/thematic-compilations/12/songs", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/thematic-compilations/13/songs", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/thematic-compilations/14/songs", thRequestResponsesPath + "/item-content-ajax-response.html"],

  /* =========== soundtracks songs ajax simple responses ========== */      
  ["/soundtracks/1/songs", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/soundtracks/2/songs", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/soundtracks/3/songs", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/soundtracks/4/songs", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/soundtracks/5/songs", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/soundtracks/6/songs", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/soundtracks/7/songs", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/soundtracks/8/songs", thRequestResponsesPath + "/item-content-ajax-response.html"],
  
  /* =========== genres artists ajax simple responses ========== */
  ["/genres/1/artists", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/2/artists", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/3/artists", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/4/artists", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/5/artists", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/6/artists", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/7/artists", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/8/artists", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/9/artists", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/10/artists", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/11/artists", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/12/artists", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/13/artists", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/14/artists", thRequestResponsesPath + "/item-content-ajax-response.html"],
  
  /* =========== genres subgenres ajax simple responses ========== */
  ["/genres/1/subgenres", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/2/subgenres", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/3/subgenres", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/4/subgenres", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/5/subgenres", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/6/subgenres", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/7/subgenres", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/8/subgenres", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/9/subgenres", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/10/subgenres", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/11/subgenres", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/12/subgenres", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/13/subgenres", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/14/subgenres", thRequestResponsesPath + "/item-content-ajax-response.html"],

  /* =========== artists albums simple responses ========== */   
  ["/genres/1/artists/1/albums", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/1/artists/2/albums", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/1/artists/3/albums", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/1/artists/4/albums", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/1/artists/5/albums", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/1/artists/6/albums", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/1/artists/7/albums", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/1/artists/8/albums", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/1/artists/9/albums", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/1/artists/10/albums", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/1/artists/11/albums", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/1/artists/12/albums", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/1/artists/13/albums", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/1/artists/14/albums", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/1/artists/15/albums", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/1/artists/16/albums", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/1/artists/17/albums", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/1/artists/18/albums", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/1/artists/19/albums", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/1/artists/20/albums", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/1/artists/21/albums", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/1/artists/22/albums", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/1/artists/23/albums", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/1/artists/24/albums", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/1/artists/25/albums", thRequestResponsesPath + "/item-content-ajax-response.html"],
  
  /* =========== albums songs ajax simple responses ========== */   
  ["/genres/1/artists/1/albums/1/songs", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/1/artists/1/albums/2/songs", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/1/artists/1/albums/3/songs", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/1/artists/1/albums/4/songs", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/1/artists/1/albums/5/songs", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/1/artists/1/albums/6/songs", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/1/artists/1/albums/7/songs", thRequestResponsesPath + "/item-content-ajax-response.html"],
  
  /* =========== navigation ajax simple responses ========== */   
  ["/genres/3/artists/1/albums", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/genres/3/artists/1/albums/1/songs", thRequestResponsesPath + "/item-content-ajax-response.html"],
  ["/", thRequestResponsesPath + "/item-content-ajax-response.html"]
];