
compileTasksConfigs:
    - name         : Container managed classes
      compilerArgs :
          -AassumeAssertionsAreEnabled :
          -AsuppressWarnings   : initialization.fields.uninitialized
          -AonlyDefs           : &container_managed |-
                ^com.ihordev.web\..+|^com.ihordev.repository\..+|^com.ihordev.service\..+|^com.ihordev.domain\..+|^com.ihordev.config\..+

    - name         : All others
      compilerArgs :
          -AassumeAssertionsAreEnabled :
          -AskipDefs    : *container_managed
